services:
  mariadb:
    image: mariadb
    container_name: mariadb3
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: ciber
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./Jugadores.sql:/docker-entrypoint-initdb.d/Jugadores.sql:ro

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadminb3
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: 1234
    ports:
      - 7103:80
    depends_on:
      - mariadb

  python:
    build: ./api
    container_name: pythonb3
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 1234
      DB_DATABASE: ciber
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
    depends_on:
      - mariadb

  apache-waf:
    container_name: apacheb3
    build: ./apache
    ports:
      - 6103:80
    volumes:
      - ./apache:/var/www/html
    depends_on:
      - python

volumes:
  mariadb_data:

