services:
  mariadb:
    image: mariadb
    container_name: mariadbb3
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - mariadb-datab3:/var/lib/mysql
      - ./Jugadores.sql:/docker-entrypoint-initdb.d/Jugadores.sql:ro

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadminb3
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - 7103:80
    depends_on:
      - mariadb

  python:
    build: ./api
    container_name: pythonb3
    restart: unless-stopped
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      - mariadb

  apache:
    build: ./apache
    container_name: apacheb3
    restart: unless-stopped
    ports:
      - 6103:80
    depends_on:
      - python

volumes:
  mariadb-datab3:
